# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4f7095e90f733adc6e1c41f3f8c6817a1d021eaac4d133a0e10e012ff138ce4e06d3d94b7c3525c57ea5cb13bbab777338ba53f04b922ede074a751fbe08877
  aws_access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
  aws_secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
test:
  secret_key_base: c6defdbc061719fcbb8458d87d9042a581f6b4b73f43518268bbf37493ec71737ed6fe07049151aa79236734472d9c279fa21cc6abd87d237bfee3000eeac74b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
